components/filter/filter.module.css, components/filter/index.js, components/transaction-details/transaction-details.module.css, components/user-info/user-info.module.css, styles/Home.module.css
Changed CSS of transactionCard .
Changed Coin color.
Other minor changes
=> Design-changes

components/footer/index.js, pages/cart.js, pages/index.js, pages/shop/index.js, styles/globals.css
- added footer on all pages (index, shop, cart)
- styled the footer as requested by @sumitd94 
- moved the footer CSS to globals.css
- renamed the parent div with className **main-container**
- added div with className **content** to wrap everything other than footer
- styled the above mentioned classes so as to push the footer to the bottom of the screen
Thank you! This footer taught me a lot of things 😄
=> added footer on all pages with proper styling

pages/index.js, styles/Home.module.css
- Added emboss effect for the coins
- Made variables for colors
=> Coin emboss effect

components/cart-summary/index.js, components/cartlist-card/index.js, components/coins-status/index.js, components/save-later/index.js, mock/coins.json, pages/cart.js, pages/index.js, redux/action.js, redux/actionTypes.js, redux/reducers/cartdetails.js, redux/reducers/index.js, redux/reducers/savelater.js, redux/reducers/shoplist.js, redux/selector.js, styles/Home.module.css
add save-later and del from cart feat
=> add save-later and del from cart feat

components/passbook/index.js, components/passbook/passbook.module.css, mock/passbookData.json, package-lock.json, package.json, pages/passbook.js
Fixes #25 
- Added a mock json file
- Sorted the transactions by latest
- Added a bit of styling
- Added media queries
Demo:
Kindly suggest the required changes.
Thank you!
=> Passbook component with infinite scrolling

jsconfig.json, styles/globals.css
A gap below the footer message for easy clicking
=> Footer given a margin on bottom, base url updated for compiler options

CONTRIBUTING.md, components/coins-status/index.js, components/coins-status/useCoinStatus.js, components/transaction-chart/transaction-chart.module.css, components/user-info/index.js, components/user-info/user-info.module.css, jsconfig.json, mock/coins.json, package-lock.json, pages/index.js, pages/shop/[product].js, styles/Home.module.css, styles/globals.css
- Page layout fixes
- SSR Caching enabled
=> Main ⬅️ Develop

components/NavBar/index.js, components/NavBar/navbar.module.css, pages/index.js, styles/Home.module.css
NavBar component added with css changes
=> CSS change for navigation bar #63 Nav Bar Component Added

components/shoplist-card/index.js, pages/shop/index.js
Changes:
1.  Added flex to the cards to make them responsive 
2.  Changed the card style 
3.  Added on hover animation
Files changed:
1. pages/shop/index.js
2. components/shoplist-card/index.js
=> Updated the shop card

components/navbar/index.js, components/navbar/navbar.module.css, pages/index.js
=> Navbar update

components/NavBar/index.js, components/NavBar/navbar.module.css, package-lock.json, pages/index.js, styles/Home.module.css
- Main body layout fix
- It is 1st  part of layout fix.
- ## Desktop
- ## Mobile:
=> Navbar Layout Fix[1st Part]

.gitignore, components/shoplist-card/index.js, mock/receivers.json, package.json
=> Swapped position of the - and + buttons on the shop page

components/coins-status/coin.module.css, components/coins-status/index.js
Made coin status bar responsive.
=> bug: made coins-status responsive

components/cart-summary/index.js, components/cartlist-card/index.js
@Kratika0907 changes has been made for shop page responsiveness for mobile devices.
Mobile view for bill
=> responsive shop page

components/transaction-operation/index.js, components/transaction-operation/transaction-operation.module.css
On send and receive transactions, even though the dropdown was initialized with values, the states needed manual update which is fixed by initializing the first variable from the object(users,transaction currency type)
=> Send Receive transaction initialization fix

components/coins-status/coin.module.css, components/transaction-chart/transaction-chart.module.css, mock/coins.json, pages/index.js, styles/Home.module.css, styles/globals.css
@Kratika0907 Changes has been made as per new design. Please review.
Desktop View
Mobile View
=> Changing layout for dashboard

components/NavBar/index.js, components/NavBar/navbar.module.css, components/filter/filter.module.css, styles/Home.module.css
@Kratika0907 As discussed changes has been made. Please review.
Dropdown in mobile view
Added dropdown & given suitable width to filterContent
Mobile responsive transaction card
=> New layout/changes

components/Close-popup/GenericClosePopUp.js, components/NavBar/index.js, components/filter/filter.module.css, components/filter/index.js, pages/cart.js, pages/useOutsideClick.js
created new generic .js file for handling click outside modal, to close modal. which takes ref and callback function as argument.
open for suggestions.
=> bill-bug-fix-1

components/Modal/index.js, components/Modal/modal.module.css, components/cart-summary/index.js, pages/bank.js
@Kratika0907 @sumitd94 Please review PR.
Created a generic modal component. It gets closed on clicking the cancel(cross) button, on clicking outside the modal and on clicking "Esc" key.
https://user-images.githubusercontent.com/70262783/107126146-2b13b780-68d4-11eb-8496-9703e585c546.mp4
=> Checkout page

pages/index.js
Moving graph to right column as per design requirement.
=> [feature/layout-fix-87] Moving graph to right column

components/NavBar/index.js, components/NavBar/navbar.module.css, components/coins-status/coin.module.css, components/coins-status/index.js, pages/index.js, styles/Home.module.css, styles/globals.css
=> Cosmetic cleanup for one year launch

components/coins-status/coin.module.css, components/coins-status/index.js, constants.js
The expected json format ( for /wallet )
```json
{
"message": "Wallet returned successfully",
"wallet": {
"id": "xxxx",
"currencies": {
"neelam": 50,
"dinero": 5
},
"userId": "yyyy"
}
}
```
=> Integrating /wallet API

components/coins-status/index.js, package-lock.json
Changed the counting animation parameter.
=> changed counting animation parameter

pages/trading/sell.js
fixed an issue where even if the user had 0 stocks of a certain company, the stock card of that company would still show with quantity 0. so instead of that, a message saying "You don't have any stocks yet. Click below to buy some" has been added.
Issue : Display message if user does not hold any stock or have sold all of them. #206
=> Displaying a message if user does not own any stocks and is on sell stocks page.

components/filter/index.js
In this pr, I have fixed the following issue  [#173](https://github.com/Real-Dev-Squad/website-crypto/issues/173)
=> Fixed illegal use of list tag 

README.md
updated readme with installation and running steps.
=> Issue #217 Readme update

components/transaction-operation/index.js
Set the minimum send/receive amount to 1 for sending and receiving Currency Amount.
=> set minimum amount as 1
